import {
  HorseMedicalRecType,
  HorseMedicalRouteAdmin,
} from "@/Types/global-types";
export const mockProtocolsData = [
  {
    externalTreatmentProtocolId: "TRP000000030",
    personId: "P000056577",
    protocolName: "new",
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
    isDeleted: null,
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000067",
        externalTreatmentProtocolId: "TRP000000030",
        clearedToWork: false,
        clearedToRace: false,
        recType: "DRUG_ADMINISTERED",
        vaccine: "",
        drugName: "",
        drugRoute: "INTRALESIONAL",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
    ],
  },
  {
    externalTreatmentProtocolId: "TRP000000039",
    personId: "P000056577",
    protocolName: "my_2",
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
    isDeleted: null,
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000076",
        externalTreatmentProtocolId: "TRP000000039",
        clearedToWork: false,
        clearedToRace: false,
        recType: "IMAGING",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "BoneScan",
        testName: "",
        testResults: "my results",
        limbTreated: "BH",
        notes: "my imaging Notes",
        structure: "great",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
    ],
  },
  {
    externalTreatmentProtocolId: "TRP000000049",
    personId: "P000056577",
    protocolName: "My7",
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
    isDeleted: null,
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000092",
        externalTreatmentProtocolId: "TRP000000049",
        clearedToWork: false,
        clearedToRace: false,
        recType: "INTRALESIONAL_INJECTION",
        vaccine: "",
        drugName: "",
        drugRoute: "IM",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
      {
        externalTreatmentTemplateId: "TPT000000094",
        externalTreatmentProtocolId: "TRP000000049",
        clearedToWork: false,
        clearedToRace: false,
        recType: "IMAGING",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "MRI",
        testName: "",
        testResults: "result",
        limbTreated: "BH",
        notes: "notes",
        structure: "structure",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
    ],
  },
  {
    externalTreatmentProtocolId: "TRP000000050",
    personId: "P000056577",
    protocolName: "NEW",
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
    isDeleted: null,
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000095",
        externalTreatmentProtocolId: "TRP000000050",
        clearedToWork: false,
        clearedToRace: false,
        recType: "ALTERNATIVE_TREATMENTS",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "Chiropractic",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "PAIN",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "BH",
        notes: "",
        structure: "struc",
        description: "desc",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
      {
        externalTreatmentTemplateId: "TPT000000096",
        externalTreatmentProtocolId: "TRP000000050",
        clearedToWork: false,
        clearedToRace: false,
        recType: "DENTAL",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "DESC",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
      },
    ],
  },
];

export const mappedProtocolsData = [
  {
    treatmentProtocolId: "TRP000000050",
    protocolName: "NEW",
    personId: "P000056577",
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000095",
        externalTreatmentProtocolId: "TRP000000050",
        clearedToWork: false,
        clearedToRace: false,
        recType: "AlternativeTreatments",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "Chiropractic",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "PAIN",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "BH",
        notes: "",
        structure: "struc",
        description: "desc",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000095",
        treatmentProtocolId: "TRP000000050",
      },
      {
        externalTreatmentTemplateId: "TPT000000096",
        externalTreatmentProtocolId: "TRP000000050",
        clearedToWork: false,
        clearedToRace: false,
        recType: "Dental",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "DESC",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000096",
        treatmentProtocolId: "TRP000000050",
      },
    ],
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
  },
  {
    treatmentProtocolId: "TRP000000049",
    protocolName: "My7",
    personId: "P000056577",
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000092",
        externalTreatmentProtocolId: "TRP000000049",
        clearedToWork: false,
        clearedToRace: false,
        recType: "IntralesionalInjection",
        vaccine: "",
        drugName: "",
        drugRoute: "IM",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000092",
        treatmentProtocolId: "TRP000000049",
      },
      {
        externalTreatmentTemplateId: "TPT000000094",
        externalTreatmentProtocolId: "TRP000000049",
        clearedToWork: false,
        clearedToRace: false,
        recType: "Imaging",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "MRI",
        testName: "",
        testResults: "result",
        limbTreated: "BH",
        notes: "notes",
        structure: "structure",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000094",
        treatmentProtocolId: "TRP000000049",
      },
    ],
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
  },
  {
    treatmentProtocolId: "TRP000000039",
    protocolName: "my_2",
    personId: "P000056577",
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000076",
        externalTreatmentProtocolId: "TRP000000039",
        clearedToWork: false,
        clearedToRace: false,
        recType: "Imaging",
        vaccine: "",
        drugName: "",
        drugRoute: "IV",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "pain",
        modality: "BoneScan",
        testName: "",
        testResults: "my results",
        limbTreated: "BH",
        notes: "my imaging Notes",
        structure: "great",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000076",
        treatmentProtocolId: "TRP000000039",
      },
    ],
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
  },
  {
    treatmentProtocolId: "TRP000000030",
    protocolName: "new",
    personId: "P000056577",
    treatments: [
      {
        externalTreatmentTemplateId: "TPT000000067",
        externalTreatmentProtocolId: "TRP000000030",
        clearedToWork: false,
        clearedToRace: false,
        recType: "DrugAdministered",
        vaccine: "",
        drugName: "",
        drugRoute: "Intralesional",
        drugDosage: "",
        procedure: "",
        surgery: "",
        dental: "",
        physiotherapy: "",
        chiropractic: "",
        conditionTreated: "",
        modality: "",
        testName: "",
        testResults: "",
        limbTreated: "",
        notes: "",
        structure: "",
        description: "",
        classifiedAs: null,
        category: null,
        internalNotes: null,
        isDeleted: false,
        treatmentTemplateId: "TPT000000067",
        treatmentProtocolId: "TRP000000030",
      },
    ],
    isPublic: false,
    createdDateTime: null,
    lastUpdatedDateTime: null,
  },
];

export const protocol_1 = {
  treatmentProtocolId: "TRP000000045",
  protocolName: "my 1",
  personId: "P000343598",
  treatments: [
    {
      externalTreatmentTemplateId: "TPT000000082",
      externalTreatmentProtocolId: "TRP000000045",
      clearedToWork: false,
      clearedToRace: false,
      recType: "Dental",
      vaccine: "",
      drugName: "",
      drugRoute: "IV",
      drugDosage: "",
      procedure: "",
      surgery: "",
      dental: "",
      physiotherapy: "",
      chiropractic: "",
      conditionTreated: "TBD",
      modality: "",
      testName: "",
      testResults: "res",
      limbTreated: "",
      notes: "",
      structure: "",
      description: "descr",
      classifiedAs: null,
      category: null,
      internalNotes: null,
      isDeleted: false,
      treatmentTemplateId: "TPT000000082",
      treatmentProtocolId: "TRP000000045",
    },
  ],
  isPublic: false,
  createdDateTime: null,
  lastUpdatedDateTime: null,
};

export const protocol_2 = {
  treatmentProtocolId: "TRP000000040",
  protocolName: "NEW",
  personId: "P000343598",
  treatments: [
    {
      externalTreatmentTemplateId: "TPT000000077",
      externalTreatmentProtocolId: "TRP000000040",
      clearedToWork: false,
      clearedToRace: false,
      recType: "AlternativeTreatments",
      vaccine: "",
      drugName: "",
      drugRoute: "IV",
      drugDosage: "",
      procedure: "Physio Therapy",
      surgery: "",
      dental: "",
      physiotherapy: "",
      chiropractic: "",
      conditionTreated: "PAIN",
      modality: "",
      testName: "",
      testResults: "",
      limbTreated: "BF",
      notes: "notes",
      structure: "some structure",
      description: "correct",
      classifiedAs: null,
      category: null,
      internalNotes: null,
      isDeleted: false,
      treatmentTemplateId: "TPT000000077",
      treatmentProtocolId: "TRP000000040",
    },
  ],
  isPublic: false,
  createdDateTime: null,
  lastUpdatedDateTime: null,
};

export const treatments = [
  {
    externalTreatmentTemplateId: "TPT000000077",
    externalTreatmentProtocolId: "TRP000000040",
    clearedToWork: false,
    clearedToRace: false,
    recType: "AlternativeTreatments",
    vaccine: "",
    drugName: "",
    drugRoute: "IV",
    drugDosage: "",
    procedure: "Physio Therapy",
    surgery: "",
    dental: "",
    physiotherapy: "",
    chiropractic: "",
    conditionTreated: "PAIN",
    modality: "",
    testName: "",
    testResults: "",
    limbTreated: "BF",
    notes: "notes",
    structure: "some structure",
    description: "correct",
    classifiedAs: null,
    category: null,
    internalNotes: null,
    isDeleted: false,
    treatmentTemplateId: "TPT000000077",
    treatmentProtocolId: "TRP000000040",
  },
  {
    externalTreatmentTemplateId: "TPT000000082",
    externalTreatmentProtocolId: "TRP000000045",
    clearedToWork: false,
    clearedToRace: false,
    recType: "Dental",
    vaccine: "",
    drugName: "",
    drugRoute: "IV",
    drugDosage: "",
    procedure: "",
    surgery: "",
    dental: "",
    physiotherapy: "",
    chiropractic: "",
    conditionTreated: "TBD",
    modality: "",
    testName: "",
    testResults: "res",
    limbTreated: "",
    notes: "",
    structure: "",
    description: "descr",
    classifiedAs: null,
    category: null,
    internalNotes: null,
    isDeleted: false,
    treatmentTemplateId: "TPT000000082",
    treatmentProtocolId: "TRP000000045",
  },
];

export const treatment = [
  {
    externalTreatmentTemplateId: "TPT000000077",
    externalTreatmentProtocolId: "TRP000000040",
    clearedToWork: false,
    clearedToRace: false,
    recType: "AlternativeTreatments",
    vaccine: "",
    drugName: "",
    drugRoute: "IV",
    drugDosage: "",
    procedure: "Physio Therapy",
    surgery: "",
    dental: "",
    physiotherapy: "",
    chiropractic: "",
    conditionTreated: "PAIN",
    modality: "",
    testName: "",
    testResults: "",
    limbTreated: "BF",
    notes: "notes",
    structure: "some structure",
    description: "correct",
    classifiedAs: null,
    category: null,
    internalNotes: null,
    isDeleted: false,
    treatmentTemplateId: "TPT000000077",
    treatmentProtocolId: "TRP000000040",
  },
];

export const mockVariables = {
  personId: "P000343598",
  treatments: [
    {
      recType: "AlternativeTreatments",
      vaccine: "",
      drugName: "",
      drugRoute: "IV",
      drugDosage: "",
      procedure: "Chiropractic",
      surgery: "",
      dental: "",
      physiotherapy: "",
      chiropractic: "",
      conditionTreated: "Pain",
      modality: "",
      testName: "",
      testResults: "",
      limbTreated: "BF",
      notes: "my test notes",
      structure: "grate structure",
      description: "",
      treatmentTemplateId: "e5aeba76-b31f-4566-9078-a4643a0db71a",
    },
  ],
  isPublic: false,
  protocolName: "new_Protocol",
};

export const mockCreateTreatmentProtocolResponse = {
  treatmentProtocolId: "TRP000000052",
  personId: "P000343598",
  protocolName: "new",
  treatments: [
    {
      treatmentTemplateId: "TPT000000098",
      treatmentProtocolId: "TRP000000052",
      clearedToWork: false,
      clearedToRace: false,
      recType: "DispensedMeds",
      vaccine: "",
      drugName: "Acetylcycteine",
      drugRoute: "IV",
      drugDosage: "123mg",
      procedure: "",
      surgery: "",
      dental: "",
      physiotherapy: "",
      chiropractic: "",
      conditionTreated: "pain",
      modality: "",
      testName: "",
      testResults: "",
      limbTreated: "",
      notes: "test notes",
      structure: "",
      description: "",
      classifiedAs: null,
      category: null,
      internalNotes: null,
    },
  ],
  isPublic: false,
  createdDateTime: null,
  lastUpdatedDateTime: null,
};

export const mockFavorites = [
  {
    locationId: "L000027913",
    locationName: "ABC Practice",
    latLng: "-73.98844,40.7484",
    type: "VetPractice",
    address: {
      street: "W 32nd St",
      city: "New York",
      state: "NY",
      zipPostalCode: "10001",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "",
  },
  {
    locationId: "L000027910",
    locationName: "Another Practice",
    latLng: "21.38678,-157.79278",
    type: "VetPractice",
    address: {
      street: "HI-83",
      city: "Kaneohe",
      state: "HI",
      zipPostalCode: "96744",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "",
  },
  {
    locationId: "L000011164",
    locationName: "CC Perkinson ",
    latLng: "",
    type: "Other",
    address: {
      street: "135 Sommerville St S",
      city: "Shakopee",
      state: "MN",
      zipPostalCode: "55379",
      country: "USA",
      unitAptBoxNumber: "294",
    },
    phone: "",
  },
  {
    locationId: "L000027911",
    locationName: "Gonzalez Best Practice",
    latLng: "-73.9902,40.75412",
    type: "VetPractice",
    address: {
      street: "W 38th St",
      city: "New York",
      state: "NY",
      zipPostalCode: "10018",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "",
  },
  {
    locationId: "L000026656",
    locationName: "Herbal Practice",
    latLng: "37.79139,-122.39768",
    type: "VetPractice",
    address: {
      street: "333 Market St",
      city: "San Francisco",
      state: "CA",
      zipPostalCode: "94105",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "",
  },
  {
    locationId: "L000097085",
    locationName: "S.Rosales Vet Practice",
    latLng: "64.92303,-147.85579",
    type: "VetPractice",
    address: {
      street: "Yellowsnow Rd",
      city: "Fairbanks",
      state: "AK",
      zipPostalCode: "99709",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "",
  },
  {
    locationId: "L000196899",
    locationName: "Vanessa Practice",
    latLng: "37.78215,-122.40572",
    type: "VetPractice",
    address: {
      street: "5th St",
      city: "San Francisco",
      state: "CA",
      zipPostalCode: "94103",
      country: "USA",
      unitAptBoxNumber: "",
    },
    phone: "+14796584333",
  },
];

export const mockProtocolListItem = {
  externalTreatmentTemplateId: "TPT000000019",
  externalTreatmentProtocolId: "TRP000000014",
  clearedToWork: false,
  clearedToRace: false,
  recType: HorseMedicalRecType.Surgery,
  vaccine: "",
  drugName: "",
  drugRoute: HorseMedicalRouteAdmin.IV,
  drugDosage: "",
  procedure: "",
  surgery: "",
  dental: "",
  physiotherapy: "",
  chiropractic: "",
  conditionTreated: "Arytenoid Paralysis",
  modality: "",
  testName: "",
  testResults: "positive",
  limbTreated: "BF",
  notes: "",
  structure: "Something to structure",
  description: "Nothing to describe",
  classifiedAs: null,
  category: null,
  internalNotes: null,
  isDeleted: false,
  treatmentTemplateId: "TPT000000019",
  treatmentProtocolId: "TRP000000014",
};
