export enum TRunnersResultActions {
  RUNNERSRESULT_REQUEST_BY_ID = "persons/RUNNERSRESULT_BY_ID_REQUEST",
  RUNNERSRESULT_REQUEST_BY_ID_SEND = "persons/RUNNERSRESULT_BY_ID_REQUEST_SEND",
  RUNNERSRESULT_SYNC = "persons/RUNNERSRESULT_SYNC",
  RUNNERSRESULT_SEARCH = "persons/RUNNERSRESULT_SEARCH",
}
