export enum TPersonsActions {
  PERSONS_REQUEST_BY_ID = "persons/PERSONS_BY_ID_REQUEST",
  PERSONS_REQUEST_BY_ID_SEND = "persons/PERSONS_BY_ID_REQUEST_SEND",
  PERSONS_SYNC = "persons/PERSONS_SYNC",
  PERSONS_SEARCH = "persons/PERSONS_SEARCH",
}
