export const dummyData = [
  {
    "id": "2022-07-01#3#10119209",
    "timestamp": "2025-10-24 02:35:12.522125",
    "currentAsOf": "2025-10-24 02:35:12.522125",
    "currentAsOfIncremental": 1761273312,
    "hisaCriteriaRace": false,
    "locationId": null,
    "raceClaimingPrice": 0,
    "raceCondition": "Good",
    "raceCountry": "ENG",
    "raceCourse": "Turf",
    "raceDate": "2022-07-01",
    "raceDescription": "NOVICE WEIGHT FOR AGE",
    "raceDistance": "About 1 1/2 Miles",
    "raceDistanceFurlong": "11.99998800000208",
    "raceDistanceFurlongRound": 12,
    "raceFootnote": null,
    "raceOffTime": null,
    "racePostTime": null,
    "racePurse": 19486,
    "raceRaceNumber": 3,
    "raceTrackId": "DON",
    "raceTrackName": "DONCASTER",
    "raceType": " WN",
    "starterClaimedPriceUsa": "0.0000",
    "starterClaimIndicator": "N",
    "starterClaimingPriceWaived": null,
    "starterDnf": false,
    "starterEarnings": 0,
    "starterHisaRegulated": null,
    "starterHorseBreedType": "TB",
    "starterHorseColor": "Chestnut",
    "starterHorseDamName": "Rose Brook (IRE)",
    "starterHorseFoaled": "2016-04-29",
    "starterHorseHisaId": "H000049659",
    "starterHorseMicrochips": "985101045283445",
    "starterHorseName": "Gordon's Jet (IRE)",
    "starterHorseReferenceNumber": 10119209,
    "starterHorseRegistry": "T",
    "starterHorseSex": "Gelding",
    "starterHorseSireName": "Jet Away (GB)",
    "starterHorseTattoo": "",
    "starterJockeyFirstName": "Ben",
    "starterJockeyHisaId": "P999999994",
    "starterJockeyLastName": "Robinson",
    "starterJockeyReferenceNumber": 165435,
    "starterJockeyType": "JF",
    "starterLengthBehindAtFinish": 13.35,
    "starterOdds": 18,
    "starterOfficialPosition": 6,
    "starterOwnerFirstName": "",
    "starterOwnerHisaId": "P999999988",
    "starterOwnerLastName": "Mr P. Boyle",
    "starterOwnerReferenceNumber": 2213303,
    "starterOwnerType": "OF",
    "starterPositionAtPointOfCall1": 0,
    "starterPositionAtPointOfCall2": 0,
    "starterPositionAtPointOfCall3": 0,
    "starterPositionAtPointOfCall4": 0,
    "starterPositionAtPointOfCall5": 0,
    "starterPostPosition": 4,
    "starterProgramNumber": null,
    "starterRecordType": "result",
    "starterScratched": false,
    "starterShakes": 0,
    "starterTrainerFirstName": "Brian",
    "starterTrainerHisaId": "P999999989",
    "starterTrainerLastName": "Ellison",
    "starterTrainerReferenceNumber": 143419,
    "starterTrainerType": "TF",
    "starterVoidIndicator": "N",
    "starterVoidReason": null
  },
  {
    "id": "2022-07-07#6#10624683",
    "timestamp": null,
    "currentAsOf": null,
    "currentAsOfIncremental": 1761273312,
    "hisaCriteriaRace": false,
    "locationId": null,
    "raceClaimingPrice": null,
    "raceCondition": null,
    "raceCountry": null,
    "raceCourse": null,
    "raceDate": "2022-07-07",
    "raceDescription": null,
    "raceDistance": "About",
    "raceDistanceFurlong": "7.0",
    "raceDistanceFurlongRound": null,
    "raceFootnote": null,
    "raceOffTime": null,
    "racePostTime": null,
    "racePurse": 12876,
    "raceRaceNumber": 6,
    "raceTrackId": "DON",
    "raceTrackName": "DONCASTER",
    "raceType": null,
    "starterClaimedPriceUsa": "0.0000",
    "starterClaimIndicator": "N",
    "starterClaimingPriceWaived": null,
    "starterDnf": false,
    "starterEarnings": null,
    "starterHisaRegulated": null,
    "starterHorseBreedType": "TB",
    "starterHorseColor": null,
    "starterHorseDamName": "Initially (GB)",
    "starterHorseFoaled": null,
    "starterHorseHisaId": null,
    "starterHorseMicrochips": "985101045318070",
    "starterHorseName": null,
    "starterHorseReferenceNumber": 10624683,
    "starterHorseRegistry": "T",
    "starterHorseSex": "Gelding",
    "starterHorseSireName": null,
    "starterHorseTattoo": "",
    "starterJockeyFirstName": "Daniel",
    "starterJockeyHisaId": "P999999994",
    "starterJockeyLastName": "Tudhope",
    "starterJockeyReferenceNumber": null,
    "starterJockeyType": "JF",
    "starterLengthBehindAtFinish": 3.25,
    "starterOdds": null,
    "starterOfficialPosition": null,
    "starterOwnerFirstName": null,
    "starterOwnerHisaId": "P999999988",
    "starterOwnerLastName": "Julie and David R Martin and Dan Hall",
    "starterOwnerReferenceNumber": 2163862,
    "starterOwnerType": "OF",
    "starterPositionAtPointOfCall1": 0,
    "starterPositionAtPointOfCall2": 0,
    "starterPositionAtPointOfCall3": 0,
    "starterPositionAtPointOfCall4": 0,
    "starterPositionAtPointOfCall5": 0,
    "starterPostPosition": null,
    "starterProgramNumber": null,
    "starterRecordType": null,
    "starterScratched": null,
    "starterShakes": 0,
    "starterTrainerFirstName": null,
    "starterTrainerHisaId": null,
    "starterTrainerLastName": null,
    "starterTrainerReferenceNumber": 970471,
    "starterTrainerType": null,
    "starterVoidIndicator": "N",
    "starterVoidReason": null
  }
]
