export enum THorsesActions {
  // SEARCH_HORSE_REQUEST = 'horses/SEARCH_HORSE_REQUEST',
  // SEARCH_HORSE_REQUEST_SEND = 'horses/SEARCH_HORSE_REQUEST_SEND',
  // SEARCH_HORSE_BY_ID_REQUEST = 'horses/SEARCH_HORSE_BY_ID_REQUEST',
  // SEARCH_HORSE_BY_ID_REQUEST_SEND = 'horses/SEARCH_HORSE_BY_ID_REQUEST_SEND',
  GET_HORSE_BY_PERSON_REQUEST = 'horses/GET_HORSE_BY_PERSON_REQUEST',
  GET_HORSE_BY_PERSON_REQUEST_SEND = 'horses/GET_HORSE_BY_PERSON_REQUEST_SEND',
  // SEARCH_HORSE_BY_IDS_REQUEST = 'horses/SEARCH_HORSE_BY_IDS_REQUEST',
  // SEARCH_HORSE_BY_IDS_REQUEST_SEND = 'horses/SEARCH_HORSE_BY_IDS_REQUEST_SEND',
  // SYNC_HORSE_BY_ID = 'horses/SYNC_HORSE_BY_ID',
}
