export enum TLocationsActions {
  LOCATIONS_REQUEST = "locations/LOCATIONS_REQUEST",
  LOCATIONS_REQUEST_SEND = "locations/LOCATIONS_REQUEST_SEND",
  LOCATIONS_SUCCESS = "locations/LOCATIONS_SUCCESS",
  LOCATIONS_FAILURE = "locations/LOCATIONS_FAILURE",
  SYNC_LOCATION = "locations/SYNC_LOCATION",
  LOCATIONS_REQUEST_BY_ID = "locations/LOCATIONS_BY_ID_REQUEST",
  LOCATIONS_REQUEST_BY_ID_SEND = "locations/LOCATIONS_BY_ID_REQUEST_SEND",
  LOCATIONS_SYNC = "locations/LOCATIONS_SYNC",
  ADDRESS_REQUEST_SEND = "locations/ADDRESS_REQUEST_SEND",
  LOCATIONS_NEAREST_REQUEST = "locations/LOCATIONS_NEAREST_REQUEST",
  ADD_TO_USER_SETTINGS_REQUEST_SEND = "locations/ADD_TO_USER_SETTINGS_REQUEST_SEND",
  USER_SETTINGS_REQUEST_SEND = "locations/USER_SETTINGS_REQUEST_SEND",
}
