export enum TreatmentProtocolsActions {
  CREATE_PROTOCOL = "protocol/CREATE_PROTOCOL",
  GET_ALL_PROTOCOLS = "protocol/GET_ALL_PROTOCOLS",
  ADD_TO_PROTOCOL = "protocol/ADD_TO_PROTOCOL",
  EDIT_PROTOCOL = "protocol/EDIT_PROTOCOL",
  DELETE_PROTOCOL = "protocol/DELETE_PROTOCOL",
  DELETE_FROM_PROTOCOL = "protocol/DELETE_FROM_PROTOCOL",
  UPDATE_TREATMENT_TEMPLATE = "protocol/UPDATE_TREATMENT_TEMPLATE",
  GET_PROTOCOL_BY_ID = "protocol/GET_PROTOCOL_BY_ID",
  UPDATE_PROTOCOL_NAME = "protocol/UPDATE_PROTOCOL_NAME",
}
